services:
  web:
    image: ${IMAGE_NAME}
    ports:
      - target: 8380
        published: 8380
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
